/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.wkh.fastblog.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Post extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Post\",\"namespace\":\"org.wkh.fastblog.domain\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"initial_offset\",\"type\":\"long\"},{\"name\":\"created_at\",\"type\":\"long\"},{\"name\":\"published\",\"type\":\"boolean\"},{\"name\":\"published_at\",\"type\":\"long\"},{\"name\":\"updated_at\",\"type\":\"long\"},{\"name\":\"title\",\"type\":\"string\"},{\"name\":\"body\",\"type\":\"string\"},{\"name\":\"summary\",\"type\":\"string\"},{\"name\":\"title_slug\",\"type\":\"string\"},{\"name\":\"slug\",\"type\":\"string\"},{\"name\":\"soft_deleted\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence id;
  @Deprecated public long initial_offset;
  @Deprecated public long created_at;
  @Deprecated public boolean published;
  @Deprecated public long published_at;
  @Deprecated public long updated_at;
  @Deprecated public java.lang.CharSequence title;
  @Deprecated public java.lang.CharSequence body;
  @Deprecated public java.lang.CharSequence summary;
  @Deprecated public java.lang.CharSequence title_slug;
  @Deprecated public java.lang.CharSequence slug;
  @Deprecated public boolean soft_deleted;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Post() {}

  /**
   * All-args constructor.
   */
  public Post(java.lang.CharSequence id, java.lang.Long initial_offset, java.lang.Long created_at, java.lang.Boolean published, java.lang.Long published_at, java.lang.Long updated_at, java.lang.CharSequence title, java.lang.CharSequence body, java.lang.CharSequence summary, java.lang.CharSequence title_slug, java.lang.CharSequence slug, java.lang.Boolean soft_deleted) {
    this.id = id;
    this.initial_offset = initial_offset;
    this.created_at = created_at;
    this.published = published;
    this.published_at = published_at;
    this.updated_at = updated_at;
    this.title = title;
    this.body = body;
    this.summary = summary;
    this.title_slug = title_slug;
    this.slug = slug;
    this.soft_deleted = soft_deleted;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return initial_offset;
    case 2: return created_at;
    case 3: return published;
    case 4: return published_at;
    case 5: return updated_at;
    case 6: return title;
    case 7: return body;
    case 8: return summary;
    case 9: return title_slug;
    case 10: return slug;
    case 11: return soft_deleted;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: initial_offset = (java.lang.Long)value$; break;
    case 2: created_at = (java.lang.Long)value$; break;
    case 3: published = (java.lang.Boolean)value$; break;
    case 4: published_at = (java.lang.Long)value$; break;
    case 5: updated_at = (java.lang.Long)value$; break;
    case 6: title = (java.lang.CharSequence)value$; break;
    case 7: body = (java.lang.CharSequence)value$; break;
    case 8: summary = (java.lang.CharSequence)value$; break;
    case 9: title_slug = (java.lang.CharSequence)value$; break;
    case 10: slug = (java.lang.CharSequence)value$; break;
    case 11: soft_deleted = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'initial_offset' field.
   */
  public java.lang.Long getInitialOffset() {
    return initial_offset;
  }

  /**
   * Sets the value of the 'initial_offset' field.
   * @param value the value to set.
   */
  public void setInitialOffset(java.lang.Long value) {
    this.initial_offset = value;
  }

  /**
   * Gets the value of the 'created_at' field.
   */
  public java.lang.Long getCreatedAt() {
    return created_at;
  }

  /**
   * Sets the value of the 'created_at' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.lang.Long value) {
    this.created_at = value;
  }

  /**
   * Gets the value of the 'published' field.
   */
  public java.lang.Boolean getPublished() {
    return published;
  }

  /**
   * Sets the value of the 'published' field.
   * @param value the value to set.
   */
  public void setPublished(java.lang.Boolean value) {
    this.published = value;
  }

  /**
   * Gets the value of the 'published_at' field.
   */
  public java.lang.Long getPublishedAt() {
    return published_at;
  }

  /**
   * Sets the value of the 'published_at' field.
   * @param value the value to set.
   */
  public void setPublishedAt(java.lang.Long value) {
    this.published_at = value;
  }

  /**
   * Gets the value of the 'updated_at' field.
   */
  public java.lang.Long getUpdatedAt() {
    return updated_at;
  }

  /**
   * Sets the value of the 'updated_at' field.
   * @param value the value to set.
   */
  public void setUpdatedAt(java.lang.Long value) {
    this.updated_at = value;
  }

  /**
   * Gets the value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }

  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'body' field.
   */
  public java.lang.CharSequence getBody() {
    return body;
  }

  /**
   * Sets the value of the 'body' field.
   * @param value the value to set.
   */
  public void setBody(java.lang.CharSequence value) {
    this.body = value;
  }

  /**
   * Gets the value of the 'summary' field.
   */
  public java.lang.CharSequence getSummary() {
    return summary;
  }

  /**
   * Sets the value of the 'summary' field.
   * @param value the value to set.
   */
  public void setSummary(java.lang.CharSequence value) {
    this.summary = value;
  }

  /**
   * Gets the value of the 'title_slug' field.
   */
  public java.lang.CharSequence getTitleSlug() {
    return title_slug;
  }

  /**
   * Sets the value of the 'title_slug' field.
   * @param value the value to set.
   */
  public void setTitleSlug(java.lang.CharSequence value) {
    this.title_slug = value;
  }

  /**
   * Gets the value of the 'slug' field.
   */
  public java.lang.CharSequence getSlug() {
    return slug;
  }

  /**
   * Sets the value of the 'slug' field.
   * @param value the value to set.
   */
  public void setSlug(java.lang.CharSequence value) {
    this.slug = value;
  }

  /**
   * Gets the value of the 'soft_deleted' field.
   */
  public java.lang.Boolean getSoftDeleted() {
    return soft_deleted;
  }

  /**
   * Sets the value of the 'soft_deleted' field.
   * @param value the value to set.
   */
  public void setSoftDeleted(java.lang.Boolean value) {
    this.soft_deleted = value;
  }

  /** Creates a new Post RecordBuilder */
  public static org.wkh.fastblog.domain.Post.Builder newBuilder() {
    return new org.wkh.fastblog.domain.Post.Builder();
  }
  
  /** Creates a new Post RecordBuilder by copying an existing Builder */
  public static org.wkh.fastblog.domain.Post.Builder newBuilder(org.wkh.fastblog.domain.Post.Builder other) {
    return new org.wkh.fastblog.domain.Post.Builder(other);
  }
  
  /** Creates a new Post RecordBuilder by copying an existing Post instance */
  public static org.wkh.fastblog.domain.Post.Builder newBuilder(org.wkh.fastblog.domain.Post other) {
    return new org.wkh.fastblog.domain.Post.Builder(other);
  }
  
  /**
   * RecordBuilder for Post instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Post>
    implements org.apache.avro.data.RecordBuilder<Post> {

    private java.lang.CharSequence id;
    private long initial_offset;
    private long created_at;
    private boolean published;
    private long published_at;
    private long updated_at;
    private java.lang.CharSequence title;
    private java.lang.CharSequence body;
    private java.lang.CharSequence summary;
    private java.lang.CharSequence title_slug;
    private java.lang.CharSequence slug;
    private boolean soft_deleted;

    /** Creates a new Builder */
    private Builder() {
      super(org.wkh.fastblog.domain.Post.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.wkh.fastblog.domain.Post.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.initial_offset)) {
        this.initial_offset = data().deepCopy(fields()[1].schema(), other.initial_offset);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.created_at)) {
        this.created_at = data().deepCopy(fields()[2].schema(), other.created_at);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.published)) {
        this.published = data().deepCopy(fields()[3].schema(), other.published);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.published_at)) {
        this.published_at = data().deepCopy(fields()[4].schema(), other.published_at);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.updated_at)) {
        this.updated_at = data().deepCopy(fields()[5].schema(), other.updated_at);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.title)) {
        this.title = data().deepCopy(fields()[6].schema(), other.title);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.body)) {
        this.body = data().deepCopy(fields()[7].schema(), other.body);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.summary)) {
        this.summary = data().deepCopy(fields()[8].schema(), other.summary);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.title_slug)) {
        this.title_slug = data().deepCopy(fields()[9].schema(), other.title_slug);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.slug)) {
        this.slug = data().deepCopy(fields()[10].schema(), other.slug);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.soft_deleted)) {
        this.soft_deleted = data().deepCopy(fields()[11].schema(), other.soft_deleted);
        fieldSetFlags()[11] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Post instance */
    private Builder(org.wkh.fastblog.domain.Post other) {
            super(org.wkh.fastblog.domain.Post.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.initial_offset)) {
        this.initial_offset = data().deepCopy(fields()[1].schema(), other.initial_offset);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.created_at)) {
        this.created_at = data().deepCopy(fields()[2].schema(), other.created_at);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.published)) {
        this.published = data().deepCopy(fields()[3].schema(), other.published);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.published_at)) {
        this.published_at = data().deepCopy(fields()[4].schema(), other.published_at);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.updated_at)) {
        this.updated_at = data().deepCopy(fields()[5].schema(), other.updated_at);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.title)) {
        this.title = data().deepCopy(fields()[6].schema(), other.title);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.body)) {
        this.body = data().deepCopy(fields()[7].schema(), other.body);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.summary)) {
        this.summary = data().deepCopy(fields()[8].schema(), other.summary);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.title_slug)) {
        this.title_slug = data().deepCopy(fields()[9].schema(), other.title_slug);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.slug)) {
        this.slug = data().deepCopy(fields()[10].schema(), other.slug);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.soft_deleted)) {
        this.soft_deleted = data().deepCopy(fields()[11].schema(), other.soft_deleted);
        fieldSetFlags()[11] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.CharSequence getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public org.wkh.fastblog.domain.Post.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public org.wkh.fastblog.domain.Post.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'initial_offset' field */
    public java.lang.Long getInitialOffset() {
      return initial_offset;
    }
    
    /** Sets the value of the 'initial_offset' field */
    public org.wkh.fastblog.domain.Post.Builder setInitialOffset(long value) {
      validate(fields()[1], value);
      this.initial_offset = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'initial_offset' field has been set */
    public boolean hasInitialOffset() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'initial_offset' field */
    public org.wkh.fastblog.domain.Post.Builder clearInitialOffset() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'created_at' field */
    public java.lang.Long getCreatedAt() {
      return created_at;
    }
    
    /** Sets the value of the 'created_at' field */
    public org.wkh.fastblog.domain.Post.Builder setCreatedAt(long value) {
      validate(fields()[2], value);
      this.created_at = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'created_at' field has been set */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'created_at' field */
    public org.wkh.fastblog.domain.Post.Builder clearCreatedAt() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'published' field */
    public java.lang.Boolean getPublished() {
      return published;
    }
    
    /** Sets the value of the 'published' field */
    public org.wkh.fastblog.domain.Post.Builder setPublished(boolean value) {
      validate(fields()[3], value);
      this.published = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'published' field has been set */
    public boolean hasPublished() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'published' field */
    public org.wkh.fastblog.domain.Post.Builder clearPublished() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'published_at' field */
    public java.lang.Long getPublishedAt() {
      return published_at;
    }
    
    /** Sets the value of the 'published_at' field */
    public org.wkh.fastblog.domain.Post.Builder setPublishedAt(long value) {
      validate(fields()[4], value);
      this.published_at = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'published_at' field has been set */
    public boolean hasPublishedAt() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'published_at' field */
    public org.wkh.fastblog.domain.Post.Builder clearPublishedAt() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'updated_at' field */
    public java.lang.Long getUpdatedAt() {
      return updated_at;
    }
    
    /** Sets the value of the 'updated_at' field */
    public org.wkh.fastblog.domain.Post.Builder setUpdatedAt(long value) {
      validate(fields()[5], value);
      this.updated_at = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'updated_at' field has been set */
    public boolean hasUpdatedAt() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'updated_at' field */
    public org.wkh.fastblog.domain.Post.Builder clearUpdatedAt() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'title' field */
    public java.lang.CharSequence getTitle() {
      return title;
    }
    
    /** Sets the value of the 'title' field */
    public org.wkh.fastblog.domain.Post.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.title = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'title' field has been set */
    public boolean hasTitle() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'title' field */
    public org.wkh.fastblog.domain.Post.Builder clearTitle() {
      title = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'body' field */
    public java.lang.CharSequence getBody() {
      return body;
    }
    
    /** Sets the value of the 'body' field */
    public org.wkh.fastblog.domain.Post.Builder setBody(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.body = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'body' field has been set */
    public boolean hasBody() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'body' field */
    public org.wkh.fastblog.domain.Post.Builder clearBody() {
      body = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'summary' field */
    public java.lang.CharSequence getSummary() {
      return summary;
    }
    
    /** Sets the value of the 'summary' field */
    public org.wkh.fastblog.domain.Post.Builder setSummary(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.summary = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'summary' field has been set */
    public boolean hasSummary() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'summary' field */
    public org.wkh.fastblog.domain.Post.Builder clearSummary() {
      summary = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'title_slug' field */
    public java.lang.CharSequence getTitleSlug() {
      return title_slug;
    }
    
    /** Sets the value of the 'title_slug' field */
    public org.wkh.fastblog.domain.Post.Builder setTitleSlug(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.title_slug = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'title_slug' field has been set */
    public boolean hasTitleSlug() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'title_slug' field */
    public org.wkh.fastblog.domain.Post.Builder clearTitleSlug() {
      title_slug = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'slug' field */
    public java.lang.CharSequence getSlug() {
      return slug;
    }
    
    /** Sets the value of the 'slug' field */
    public org.wkh.fastblog.domain.Post.Builder setSlug(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.slug = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'slug' field has been set */
    public boolean hasSlug() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'slug' field */
    public org.wkh.fastblog.domain.Post.Builder clearSlug() {
      slug = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'soft_deleted' field */
    public java.lang.Boolean getSoftDeleted() {
      return soft_deleted;
    }
    
    /** Sets the value of the 'soft_deleted' field */
    public org.wkh.fastblog.domain.Post.Builder setSoftDeleted(boolean value) {
      validate(fields()[11], value);
      this.soft_deleted = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'soft_deleted' field has been set */
    public boolean hasSoftDeleted() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'soft_deleted' field */
    public org.wkh.fastblog.domain.Post.Builder clearSoftDeleted() {
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    public Post build() {
      try {
        Post record = new Post();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.initial_offset = fieldSetFlags()[1] ? this.initial_offset : (java.lang.Long) defaultValue(fields()[1]);
        record.created_at = fieldSetFlags()[2] ? this.created_at : (java.lang.Long) defaultValue(fields()[2]);
        record.published = fieldSetFlags()[3] ? this.published : (java.lang.Boolean) defaultValue(fields()[3]);
        record.published_at = fieldSetFlags()[4] ? this.published_at : (java.lang.Long) defaultValue(fields()[4]);
        record.updated_at = fieldSetFlags()[5] ? this.updated_at : (java.lang.Long) defaultValue(fields()[5]);
        record.title = fieldSetFlags()[6] ? this.title : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.body = fieldSetFlags()[7] ? this.body : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.summary = fieldSetFlags()[8] ? this.summary : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.title_slug = fieldSetFlags()[9] ? this.title_slug : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.slug = fieldSetFlags()[10] ? this.slug : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.soft_deleted = fieldSetFlags()[11] ? this.soft_deleted : (java.lang.Boolean) defaultValue(fields()[11]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
